### ISSUE TITLE
CJS to CJS doesn't run through normalize.

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/transpile#19]
This is true of probably everything to itself except amd to amd.

**Comment by matthewp** [comment]
Wasn't the need for amd to amd to inside the named defines?  What would be the purpose for other formats like cjs?

**Comment by justinbmeyer** [comment]
also to run normalize

**Comment by matthewp** [comment]
@ccummings has a need for this so i'm going to go ahead and fix it.
